version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: max_bot
    command: python -m bot.main
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - max_net

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: max_cron
    command: python -m cronjobs.main
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - max_net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: max_bot
      POSTGRES_PASSWORD: max_bot
      POSTGRES_DB: max_timetable
    ports:
      - "9005:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - max_net

networks:
  max_net:
    driver: bridge
